### ISSUE TITLE
Typo for ValueMappingInService

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-process-orchestration-migration-guide#12]
### Issue description

Page says:
**ValueMappingInService**
With the ValueMappingIn API, you get detailed information about the **sender agreement**.

### Feedback Type (Optional)

spelling or grammar

### Page Title on SAP Help Portal (prefilled)

Directory API

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/MIGRATION_GUIDE_PO/90c8ad90cb684ee5979856093efe7462/07096c2752c64dbd8bfdb23923087a23.html

**Comment by MelanieCueppers** [comment]
Hi @freest5, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MelanieCueppers** [comment]
I've corrected the typo and the correction will be published soon. Thanks again for your valuable feedback!
