### ISSUE TITLE
Hybrid deployment option IS available now! 

### ISSUE THREAD

**Issue by fippu82** [SAP-docs/btp-process-orchestration-migration-guide#13]
### Issue description

Please update page. Edge Cell is there now. 

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Cloud Middleware

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/migration-guide-po/migration-guide-for-sap-process-orchestration/cloud-middleware?locale=en-US

**Comment by MelanieCueppers** [comment]
Hi @fippu82, thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MelanieCueppers** [comment]
Our content team will updated the page in the near future. For now, we've hidden the affected pages with the incorrect information. 
Thank you again for your feedback!

**Comment by fippu82** [comment]
165304
