### ISSUE TITLE
Wrong comment for OData adapter

### ISSUE THREAD

**Issue by freest5** [SAP-docs/btp-process-orchestration-migration-guide#14]
### Issue description

For OData adapter the Restrictions/Alternatives column is "SAP is working on supporting multiple cloud and on-premise **database** vendors."
It looks like mistake in description for OData adapter, more like for JDBC?

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Standard Adapter Migration

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/migration-guide-po/migration-guide-for-sap-process-orchestration/standard-adapter-migration

**Comment by MelanieCueppers** [comment]
Hi @freest5 , thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MelanieCueppers** [comment]
Hi @freest5, the incorrect statement has been removed. Thank you again for your feedback!
