### ISSUE TITLE
Feedback for "Transition to SAP Integration Suite"

### ISSUE THREAD

**Issue by lrcherubini** [SAP-docs/btp-process-orchestration-migration-guide#8]
https://help.sap.com/docs/help/90c8ad90cb684ee5979856093efe7462/0efebfbaeeb2408e80a12aae083d400e.html?locale=en-US

Here:

"A [Future-proof Integration Strategy](https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fwww.sap.com%2Fdocuments%2F2020%2F07%2Fb00a39ed-a07d-0010-87a3-c30de2ffd8ff.html)Information published on SAP site ensures that organizations are prepared for the next steps in their digital transformation journeys. It's critical for organizations to factor this into the overall strategy to control costs and encourage innovation at the same time."

That link "Future-proof Integration Strategy" is broke.

Thanks.

**Comment by MelanieCueppers** [comment]
Hi Leandro,
thanks for your feedback! We'll look into the issue as soon as possible.
Kind regards
Melanie

**Comment by MelanieCueppers** [comment]
Hi Leandro, thanks again for your contribution! We currently have no replacement for the broken link, so we've removed it for now. We'll update the documentation as soon as there's a fitting replacement. 
Have a good day! 
Melanie

**Comment by lrcherubini** [comment]
https://people.sap.com/leandro.oneda

Em sex., 17 de fev. de 2023 às 07:01, sap-doc-bot[bot] <
***@***.***> escreveu:

**Comment by MelanieCueppers** [comment]
https://people.sap.com/leandro.oneda
